// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjcr7NrOnmkuGjVqYkfHJStLQBDludxWg',
    appId: '1:316829095629:web:4aac4572959e4dc80c3b84',
    messagingSenderId: '316829095629',
    projectId: 'expense-tracker-c6ab4',
    authDomain: 'expense-tracker-c6ab4.firebaseapp.com',
    storageBucket: 'expense-tracker-c6ab4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMtUzygmf2L_fhiunqGLIzQ_XrDVa8hQ',
    appId: '1:316829095629:android:0c409bb49b253d1c0c3b84',
    messagingSenderId: '316829095629',
    projectId: 'expense-tracker-c6ab4',
    storageBucket: 'expense-tracker-c6ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZlUEE3OwvX-wQfQljO9NG_0AA4CWjds',
    appId: '1:316829095629:ios:4a8fe93de7d715580c3b84',
    messagingSenderId: '316829095629',
    projectId: 'expense-tracker-c6ab4',
    storageBucket: 'expense-tracker-c6ab4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZlUEE3OwvX-wQfQljO9NG_0AA4CWjds',
    appId: '1:316829095629:ios:4a8fe93de7d715580c3b84',
    messagingSenderId: '316829095629',
    projectId: 'expense-tracker-c6ab4',
    storageBucket: 'expense-tracker-c6ab4.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjcr7NrOnmkuGjVqYkfHJStLQBDludxWg',
    appId: '1:316829095629:web:fd787c0a9957df3e0c3b84',
    messagingSenderId: '316829095629',
    projectId: 'expense-tracker-c6ab4',
    authDomain: 'expense-tracker-c6ab4.firebaseapp.com',
    storageBucket: 'expense-tracker-c6ab4.firebasestorage.app',
  );
}
